### ISSUE TITLE
TypeError: login() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by phanlipo** [shanet/Google-Music-Playlist-Sync#3]
After type password, it gives a traceback:

Logging in...
Traceback (most recent call last):
  File "/../google-music-playlist-sync.py", line 419, in <module>
    main()
  File "/../google-music-playlist-sync.py", line 57, in main
    api = login_to_google_music(user)
  File "/../google-music-playlist-sync.py", line 123, in login_to_google_music
    if api.login(user, password):
TypeError: login() takes exactly 4 arguments (3 given)

**Comment by shanet** [comment]
Looks like `login()` now takes a third param. https://unofficial-google-music-api.readthedocs.org/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login

**Comment by shanet** [comment]
Fixed, but I'm getting this when running:
```
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```
That's from the gmusicapi library though.
